[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["P1 ower <p1ower@gmx.de>"]
requires-python = ">=3.11"
dependencies = [
    "colorama>=0.4.6",
    "discord-py>=2.6.4",
    "matplotlib>=3.10.8",
]
